name: Experiment
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  experiment:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: '6.1.0'
      - name: Execute Experiment (macOS)
        if: runner.os == 'macOS'
        run: xcrun --sdk macosx swift ./experiment.swift
      - name: Execute Experiment (Linux)
        if: runner.os == 'Linux'
        run: swiftc ./experiment.swift && ./experiment
      - name: Execute Experiment (Windows)
        if: runner.os == 'Windows'
        run: swiftc ./experiment.swift && .\experiment.exe
